FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libz-dev libbz2-dev libssl-dev

COPY . /dmg2img
WORKDIR /dmg2img
ENV DESTDIR=/install
RUN make -j8 dmg2img
RUN make install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
